name: Deploy
on:
  create:
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: pavel-one/GoDeploy@master
        with:
          host: ${{secrets.HOST}}
          user: ${{secrets.USER}}
          key: ${{secrets.KEY}}
          dir: ${{secrets.DIR}}
          dbuser: notehs
          dbpassword: ${{secrets.DB_PASSWORD}}
          url: https://notehs.pavel.one